[package]
name = "pathbuster"
authors = ["zoid"]
description = "A path-normalization pentesting tool using path replacements."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
governor = "*"
futures = "*"
futures-util = "*"
tokio = { version = "^1.2.0", features = ["full"] }
colored = { version = "2.0.0" }
indicatif = "*"
spmc = "*"
clap =  { version = "^3.0.0-beta.2" }
reqwest = { version = "*", features = ["native-tls", "blocking"] }
levenshtein = "1.0.5"
urlencoding = "*"